import Navbar from "../components/Navbar"

function homePage () {
    return (
        <div className="container">
        <Navbar />
            <div className="contentContainer">
                <h1>Welcome!</h1>
                <p>Lorem ipsum dolor sit amet consectetur adipiscing elit urna, augue justo efficitur pellentesque montes venenatis torquent luctus porttitor, ex netus orci nisi scelerisque senectus cras. Congue etiam massa dis nam inceptos cubilia nisi placerat, non facilisi proin luctus consectetur rutrum quam. Himenaeos varius ac netus risus ultricies convallis arcu porttitor aptent pellentesque, sodales tortor natoque nam molestie venenatis placerat nisl sit ornare, nulla conubia scelerisque blandit ligula lorem ut porta per. Purus porta nullam convallis blandit ultricies curae finibus diam hendrerit, vitae lectus id scelerisque proin consectetur viverra ornare, magna interdum sociosqu class montes lorem praesent dictumst. Torquent vel facilisi vitae nulla donec eu, enim aliquam purus parturient odio arcu, vivamus potenti non convallis ut. Diam nostra massa eu auctor mus nisl morbi pharetra nibh lectus, mollis fermentum nascetur faucibus commodo enim consectetur tempus nam, malesuada curae elementum sed ex a mattis semper id.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipiscing elit urna, augue justo efficitur pellentesque montes venenatis torquent luctus porttitor, ex netus orci nisi scelerisque senectus cras. Congue etiam massa dis nam inceptos cubilia nisi placerat, non facilisi proin luctus consectetur rutrum quam. Himenaeos varius ac netus risus ultricies convallis arcu porttitor aptent pellentesque, sodales tortor natoque nam molestie venenatis placerat nisl sit ornare, nulla conubia scelerisque blandit ligula lorem ut porta per. Purus porta nullam convallis blandit ultricies curae finibus diam hendrerit, vitae lectus id scelerisque proin consectetur viverra ornare, magna interdum sociosqu class montes lorem praesent dictumst. Torquent vel facilisi vitae nulla donec eu, enim aliquam purus parturient odio arcu, vivamus potenti non convallis ut. Diam nostra massa eu auctor mus nisl morbi pharetra nibh lectus, mollis fermentum nascetur faucibus commodo enim consectetur tempus nam, malesuada curae elementum sed ex a mattis semper id.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipiscing elit urna, augue justo efficitur pellentesque montes venenatis torquent luctus porttitor, ex netus orci nisi scelerisque senectus cras. Congue etiam massa dis nam inceptos cubilia nisi placerat, non facilisi proin luctus consectetur rutrum quam. Himenaeos varius ac netus risus ultricies convallis arcu porttitor aptent pellentesque, sodales tortor natoque nam molestie venenatis placerat nisl sit ornare, nulla conubia scelerisque blandit ligula lorem ut porta per. Purus porta nullam convallis blandit ultricies curae finibus diam hendrerit, vitae lectus id scelerisque proin consectetur viverra ornare, magna interdum sociosqu class montes lorem praesent dictumst. Torquent vel facilisi vitae nulla donec eu, enim aliquam purus parturient odio arcu, vivamus potenti non convallis ut. Diam nostra massa eu auctor mus nisl morbi pharetra nibh lectus, mollis fermentum nascetur faucibus commodo enim consectetur tempus nam, malesuada curae elementum sed ex a mattis semper id.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipiscing elit urna, augue justo efficitur pellentesque montes venenatis torquent luctus porttitor, ex netus orci nisi scelerisque senectus cras. Congue etiam massa dis nam inceptos cubilia nisi placerat, non facilisi proin luctus consectetur rutrum quam. Himenaeos varius ac netus risus ultricies convallis arcu porttitor aptent pellentesque, sodales tortor natoque nam molestie venenatis placerat nisl sit ornare, nulla conubia scelerisque blandit ligula lorem ut porta per. Purus porta nullam convallis blandit ultricies curae finibus diam hendrerit, vitae lectus id scelerisque proin consectetur viverra ornare, magna interdum sociosqu class montes lorem praesent dictumst. Torquent vel facilisi vitae nulla donec eu, enim aliquam purus parturient odio arcu, vivamus potenti non convallis ut. Diam nostra massa eu auctor mus nisl morbi pharetra nibh lectus, mollis fermentum nascetur faucibus commodo enim consectetur tempus nam, malesuada curae elementum sed ex a mattis semper id.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipiscing elit urna, augue justo efficitur pellentesque montes venenatis torquent luctus porttitor, ex netus orci nisi scelerisque senectus cras. Congue etiam massa dis nam inceptos cubilia nisi placerat, non facilisi proin luctus consectetur rutrum quam. Himenaeos varius ac netus risus ultricies convallis arcu porttitor aptent pellentesque, sodales tortor natoque nam molestie venenatis placerat nisl sit ornare, nulla conubia scelerisque blandit ligula lorem ut porta per. Purus porta nullam convallis blandit ultricies curae finibus diam hendrerit, vitae lectus id scelerisque proin consectetur viverra ornare, magna interdum sociosqu class montes lorem praesent dictumst. Torquent vel facilisi vitae nulla donec eu, enim aliquam purus parturient odio arcu, vivamus potenti non convallis ut. Diam nostra massa eu auctor mus nisl morbi pharetra nibh lectus, mollis fermentum nascetur faucibus commodo enim consectetur tempus nam, malesuada curae elementum sed ex a mattis semper id.</p>
            </div>
        </div>
    )
};

export default homePage;